name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  CLAZY_CHECKS: "level1"

jobs:
  build:
    uses: lirios/.github/.github/workflows/build-linux.yml@master
    with:
      dependencies: umockdev-devel
